security:
    encoders:
        App\Entity\Users: bcrypt
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: username
    firewalls:
        create_token:
            pattern: ^/api/auth-token
            stateless: true
            anonymous: true
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        admin:
            pattern: ^/admin
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            user_checker: App\Security\CheckUsersRole

    access_control:
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLES_USERS: ROLES_USERS
        ROLES_ADMIN: ROLES_USERS
